#+title: Homework coaching for children

* Article: 孩子写字潦草，根本看不清写得是什么内容，一直提醒都没有什么效果，怎么才能让孩子把字写规范，写清楚认真呢?
** 方法/步骤
1、让孩子从心底里重视书写：
   孩子写作业时，总是认为作业是为老师写的，是为了应付老师检查的，快速的写完，就可以多玩一会儿，处于这种目的，很多孩子写字时写得特别的快，字自然写的就潦草了。
   让孩子明白写作业，写字是为了自己，字写得好也是对看作业人的尊重，让孩子从心底里重视写字。

2、学习正确的坐姿、书写姿势和握笔姿势：
　 很多孩子在写字时，坐的根本不正确，趴着写，歪着写，躺着写，握笔姿势也不正确，不正确的坐姿和握笔导致书写不规范，难以写出好字，因此要从小训练正确的坐姿和书写姿势。
　
3、孩子比较懒，自控能力差：
　 书写潦草的孩子一般都比较懒，沉不住气，自控能力差，总感觉写字规范比较费力，写字潦草可以省点力气，自控能力差，坐不住，光想着做其它事。
   消除孩子的懒惰心理后孩子才能写的好。

4、心不在焉，一心二用：
　 孩子书写时，心不在焉，写的什么都不清楚，有的是看着电视写作业，玩着游戏写作业，一心二用怎么能把字写好呢？所以孩子写作业时一定要静心，不能让孩子看着电视或玩着游戏写，家长也不要影响孩子。
　　
5、练习书法，修身静心;
　 让孩子练习书法，临帖，掌握字的结构，模仿他人书写，练得多了，掌握了字的结构，心也能静下来了，字就写的漂亮了。

6、常提醒常检查多鼓励;
　 家长老师都要多提醒孩子要把字写好，只要孩子动笔，就要提醒，常检查孩子的作业，鼓励孩子。

7、布置的作业适量;
　 孩子书写潦草的最大原因就是布置的作业太多了，孩子如果好好写，会用很长的时间才能完成，就没有了玩的时间，因此书写潦草，布置的作业要适量，留给孩子玩的时间，作业少了，孩子自己写得就规范了。



* Article: 家长应该如何帮助孩子改正作业潦草的坏毛病呢
专家介绍，小学生，尤其是低年级学生由于贪玩，往往会潦潦草草地完成作业，作业中经常会出现这样那样的错误，直接影响考试成绩，时间长了还会形成粗心、应付的不良习惯。
那么家长应该如何帮助孩子改正作业潦草的坏毛病呢？

** 专家总结: 预防法、榜样法、多练字帖、对比法、重写法等方法可以帮助孩子克服作业潦草的毛病。
*** 首先，家长需要了解，孩子做作业潦草的常见原因，小学生做作业潦草一般有4个原因：
- 孩子性子急躁，贪快；
- 作业繁多，急于完成；
- 贪玩，想短时间内快速完成；
- 用笔没有章法，缺少停顿，笔画起止交代不清。

*** 针对这些原因，家长可以尝试用以下几个方法帮助孩子克服作业潦草的毛病：
1、预防法。在孩子做作业前，家长提出要求，使孩子重视作业。如果孩子刚上一年级，一定要从每个细节处着手，比如拿笔的姿势，坐姿，都要严格要求，防止孩子发生潦草完成作业的现象。
2、榜样法。孩子的模仿能力很强，经常看优秀作业，会激起孩子的进取心。因此，让孩子经常看同学的优秀作业，可以帮助养成认真完成作业的良好习惯。此外，让孩子在“别的孩子能做到的，我也能做到”的心理支配下，控制自己的不良做法，养成良好的习惯。
3、多练字帖。字帖练习可以弥补孩子字写不好和性子急的不足。家长也可以让孩子学习围棋、练练毛笔字，这些对培养孩子的专注力都有很大帮助。
4、对比法。当孩子作业有了一些进步时，家长要用表扬来激励孩子继续努力，不断进步。当孩子出现退步时，用夸奖他以前的好作业来抑制错误行为。
5、重写法。如果家长经过多次诱导，孩子还是写得很潦草，那么家长需用强制的手段，让孩子重写，使孩子重视作业质量。

** 此外，父母可以提倡同学之间相互交换作业本做练习，把作业做在同桌或好友的作业本上。
每一次换做作业之后，必须签上名，这样的作业必须对同桌或好友负责，培养孩子的责任感。
通过相互交换，相互接触别的同学的作业本，促使同学间广泛地相互交流，及时改正学习中的错误，形成做作业的良性循环，有利于增强孩子的批判水平和自我约束的能力。
这样一来不分优差，大家都可为别人做榜样，连平时学习能力比较差的学生，因为作业是做在别的同学的作业本上，要给别人做榜样，所以也显得相当的认真。
总之，帮助孩子克服作业潦草的方法是很多的，具体运用时，要从实际出发，因人而异，灵活应变。


* Article: 环境和避免疲劳
　　一、 选择好学习环境,首先要让自己静下来, 选择一个安静的环境。
　　二、培养自己学习的兴趣,兴趣是最好的老师多读多看多写..
　　三、多多鼓励自己,学会一道题,记住几个公式,都要有成功感..这样才让自己有兴趣.最开心的时候用来说自己最头痛的东西...
　　四、合理安排好时间了.. 学会调节和利用自己的生物钟，事半功倍
　　五、多多注意休息,一定首先要保证休息时间 ，不搞疲劳战术..有空多来点运动,比如说打篮球\羽毛球等,跑步\散步也都好,让自己身体好,同时也可以提高学习效率..




* Article: 找出原因并以身示范
** 找出孩子写字潦草的原因对症下药
原因一：孩子比较懒，自控能力差：
书写潦草的孩子一般都比较懒，沉不住气，自控能力差，总感觉写字规范比较费力，写字潦草可以省点力气，自控能力差，坐不住，光想着做其它事。
消除孩子的懒惰心理后孩子才能写的好。
解决对策：
1、平常练习书法，修身静心;   让孩子练习书法，临帖，掌握字的结构，模仿他人书写，练得多了，掌握了字的结构，心也能静下来了，字就写的漂亮了。
2、布置的作业适量;   孩子书写潦草的最大原因就是布置的作业太多了，孩子如果好好写，会用很长的时间才能完成，就没有了玩的时间，
   因此书写潦草，布置的作业要适量，留给孩子玩的时间，作业少了，孩子自己写得就规范了。

原因二：心不在焉，一心二用
孩子书写时，心不在焉，写的什么都不清楚，有的是看着电视写作业，玩着游戏写作业，一心二用怎么能把字写好呢？
所以孩子写作业时一定要静心，不能让孩子看着电视或玩着游戏写，家长也不要影响孩子。
解决对策：
1、常提醒常检查多鼓励;   家长老师都要多提醒孩子要把字写好，只要孩子动笔，就要提醒，常检查孩子的作业，鼓励孩子。
2、让孩子从心底里重视书写：   孩子写作业时，总是认为作业是为老师写的，是为了应付老师检查的，快速的写完，就可以多玩一会儿，处于这种目的，很多孩子写字时写得特别的快，字自然写的就潦草了。
   让孩子明白写作业，写字是为了自己，字写得好也是对看作业人的尊重，让孩子从心底里重视写字。
3、培养学生用心写字的习惯   培养学生用心写字的习惯，是提高写字质量的关键所在。用心写就是学生写字时要专注、细致。
- “专注”指不可有其他杂念，不能三心二意，更不能心不在焉，
- “细致”指看清笔画，注意笔画顺序。

** 在家里或者课堂上，家长或老师可以这样培养：
1.以身示范，细致指导。以身示范指老师在板书和作业批改时，将字写规范，写端正，有时我在课堂上字写得不规范，我会坦诚地对学生说：对不起，老师这个字写得不规范，擦掉重写好吗？
  这即增添了老师的威望，也给了学生“以身作则”的学习对象，学生写字会进步更快，劲头也会更足 老师在范写生字时，要作细致指导，这个字的笔顺规则，在田字格中的位置都要讲清楚。
  也可要求学生仔细观察后说说所学的字在田字格中的位置再动笔，这样学生出错的频率就会减少。同样的，学生在家时，家长也要用类似的方法来要求孩子。
2.生动讲解，故事激趣。在写字教学中，注意生动讲解，故事激趣，使写字过程充满活生生的形象、声音、旋律。
3 老师或家长给孩子一个好榜样   给孩子展示优秀作业，激起孩子的进取心—告诉他别人能够做到的你也一定能够做到。
  另外，当孩子写作业有一定的进步的时候，一定要及时表扬和鼓励。
4 让孩子找时间多练字帖   孩子作业潦草，有的可能是写不好字，有的可能是性子急，马虎。字帖练习可以弥补这两方面的不足，再者，家长也可以让孩子学习围棋、练练毛笔字，这些对培养孩子的专注力都有很大帮助。
  “帮助孩子克服作业潦草的方法很多，具体运用时要因人而异，灵活应变。”孩子练字是一个长时间的过程，让孩子习惯写一手好字，长大后就是没有人监督，写的字也会很漂亮。
5 培养孩子正确的写好字的训练方法：
- 1．基本笔划写正确。   让小学生把基本笔划写正确并非难事，但有时学生看到的和老师讲的存在偏差，不知如何做才好。如，老师要求横平竖直，实际书写中的横一般不是平的，是长横像扁担短横微上扬。有时，印刷体与手写体也存在差异，须让学生知道哪些可以模仿哪些不可效仿。
- 2．笔顺纠正要跟上。   人们都爱走捷径，力求省时省力，小学生也不例外。写“口”，有的学生转个圈；写“连”，有的学生先写走之旁。针对笔顺错误现象一定要从一年级加强指导，及时指正。有的孩子笔顺不正确是学前写字所致，不及时纠正就会让学生被动巩固错误，一旦孩子把错误笔顺当成习惯，就难于纠正了。
- 3．培养孩子整体观。   每个汉字都有整体美，从汉字整体的高度俯视比看一个个笔画要美观许多。因此，要让孩子学会看一个字写一个字，而不是看一个笔画写一个笔画；同样，抄写词语时要看一个词语写一个词语，抄写句子时要看一句话写一句话。培养孩子的整体观念，不但有助于孩子把汉字写工整，而且有助于孩子提高写字速度。
- 4．提升孩子思维力。   形象思维和抽象思维都很重要，形象思维强，才容易产生字与字之间的联想，有助于孩子一句一句地写；抽象思维发达，能把汉字分类，才会举一反三触类旁通。培养孩子的形象思维和抽象思维能力并非仅从写字中，任何事情都可以做起。如小学低年级语文的看图写话训练就可以培养孩子的形象思维能力，而数学课程中的数字计算则是训练孩子的抽象思维能力。
- 5．让认真成为习惯。   小学生心浮气躁，稳不下心来，笔划轻浮，写出来的字必然不耐看。认真应该是伴随孩子一生的习惯，不仅写字，为人处事的各个方面都应该认真对待。同时，汉字传承的是祖国文化，写字时应该是庄重的，嘻嘻哈哈心不在焉，既是不尊重汉字也是良好习惯没有养成，写出来的字必然凌乱不堪。


* Article: 孩子拖拉是个大问题，家长应该及时帮孩子改正
作业拖延是广泛存在于学生当中的一种不良行为习惯，这种行为如果不及时得到纠正，延续到成年，会造成时间和精力的巨大浪费，效率低下，降低自尊和自信心，并伴随焦虑、内疚等消极情绪体验，
对孩子的发展和心理健康极为不利。

在这里要强调一点，对有作业拖拉行为的孩子，家长要讲究教育方法，要因材施教但不能过分严厉，尽量避免给孩子造成心理压力。

我儿子12岁，六年级。上四年级时学习任务往往不能按时完成，逐步养成了拖延逃避的坏习惯。到了五年级，要学的知识越来越多，难度也逐步加大，学业负担加重，需要投入更多时间。
但是这个时候，他的拖延行为就更加明显，在课堂上写作业时，其他同学都很认真，可他要么玩笔，要么同桌说话，要么趴桌上一动不动，就是不愿意写作业，即使老师反复提醒也无济于事。
往往是到了快下课时才开始动手写。

在写家庭作业时，我们为他提供了安静的学习环境，让他一个人独立完成，可是他在半个小时内却只写了6个字，需要我在一旁陪伴督促，即使这样，在写作业的过程中也会右顾右盼，摸东摸西。
写的字缺笔少点，遇到难题也不愿意动脑筋思考，只会向我求助完成。孩子他爸经常因为儿子不能按时完成作业而把他狠狠打一顿，无论我们怎么教育他，他依然我行我素，我们都愁死了。




* Article: 彻底解决孩子写作业拖拉磨蹭，写给每一位父母！

从进入学校第一天，孩子的生活中就多了一样叫做“作业”的东西。作业的完成情况成了家长评判孩子学习的重要工具。
回到家看到孩子的第一句话也变成了，“今天的作业写完了吗？”所以有句话说，不谈作业母慈子孝，一做作业鸡飞狗跳。

其实出现这种情况，是因为家长不知道到底该怎么做，才能让孩子写作业不拖拉。

** 一. 拖拉磨蹭的原因

1、受干扰、有诱惑力的学习环境
比如，我见过有的家庭在孩子写作业时，家长却在外面打麻将；还有些父母名义上是在陪孩子写作业，实际上却在旁边玩手机或是拿着平板打游戏。
这种有诱惑力的学习环境，很容易让孩子写作业时断时续，磨蹭拖拉。而更为科学的做法不是陪读孩子写作业，而是让孩子独立完成作业并养成自我检查的习惯。

2、家长的批评、训斥和唠叨
孩子写作业拖拉磨蹭，最直观的原因就是孩子写作业的体验感不好。
当父母看到孩子没有按时完成作业，就会对孩子加以批评、训斥和唠叨，重复多次，孩子就会把写作业这件事情和痛苦的感受连结在一起，下次孩子再遇到写作业的场景，就会直接想到被父母批评唠叨后痛苦的感受，孩子状态不好，做作业的效率自然会下降。

3、常给孩子加作业
有些家长经常有这样的想法，“孩子作业做完后，回家没事干，总拿手机打游戏，我得给他找些事干，要给他买点课外练习册做做”。
家长的出发点是促进孩子的学习，但你可能没想到，这对孩子来说是最消极的暗示。因为孩子接收到的信息是，原来我作业做得越快，爸妈就会给我布置更多的作业，那我何必呢？慢慢做，拖延一会儿是一会儿，到了该睡觉的时间，妈妈就不会再给我加作业。
所以我想提醒你，一个没有自由支配时间的孩子，是无法养成自觉习惯的。

4、父母自己做事拖延的习惯
有句话说，父母是孩子最好的老师。一个做作业磨蹭的孩子，很有可能是观察和模仿了父母后的结果。所以如果找不到别的原因，家长发现自己也有这样的毛病，不妨跟孩子相互监督，共同纠正。

** 二.解决拖拉磨蹭的方法
清楚了原因，我们就可以有针对性的做出调整和改变。而针对如何营造良好的家庭学习环境，我想给出以下几条建议：

第一，桌面管理两分法。
这个方法可以帮助孩子排除干扰，将有限的意志力量集中在作业上。
我们可以主动帮孩子处理掉桌面上与当下学习无关的东西。帮助他整理出两个区域：一个是学习区，一个是材料区。
固定桌面上学习区的用品，只保留橡皮，铅笔，尺子，并放在固定的地方，学习区只放置必要的文具和学习时使用的书本。
而材料区则可以使用“材料筐”的形式，把每一项作业和需要准备的工具提前准备好整理到筐内，放到材料区。做完一个筐放回一个筐。可以减少寻找下一项作业和材料时不必要的时间浪费和干扰。

第二，设定合理的学习时间。
比如，可以在书桌前放一个小闹钟，以每15分钟为一个单位。15分钟一到，无论作业做到哪，都要提醒孩子暂停，给孩子几分钟的放松时间。只有孩子放松好了，才能提高做作业的效率。这个方法对于低年级的孩子来说尤其重要。

第三，制定学习计划。
孩子放学回家，先别急着催促孩子写作业，而是教给孩子制订自己的学习计划，将作业进行拆解和重组，方法是将所有作业尽量拆分成15分钟左右的一个个单元，每个单元可以少于15分钟，但不能多于15分钟。
时间太长孩子注意力就集中不了，容易走神。这样做，我们把孩子每次写作业1-3个小时的时间缩短到15分钟，作业的难度瞬间降低，而孩子也能够更加集中注意力。

除此之外，还要通过成果具体化法把每天的学习规划表、完成情况等张贴在书桌的上方。
比如，每个单元完成了打“✔️”，完成不好的打“O”（不要打“X”，因为你不是为了否定孩子，而是为了激励孩子）通过视觉化和潜意识的方式，提高孩子的学习成就感。
在孩子刚开始执行时，我们要向家人或者亲戚常夸奖，及时提供正向反馈给孩子。

第四，定期跟孩子交流作业感受。
我们可以营造一个轻松的环境，定期和孩子讨论作业的问题，比如问问他今天做作业的感受。或者一周后和孩子讨论，这周写作业有什么特别收获？
或者哪些事情会分散你的注意力？下次可以在哪些方面做得更好。

第五，把惩罚变为奖励。
孩子对作业的反感不是天生的，很多孩子逐渐变得不喜欢做作业是因为作业既没挑战，也没兴趣。很多时候他明明掌握了，还要花时间去反复练习。
更不乏有些家长或老师有时还把做作业当成是惩罚的工具，把学习和教育过程变成了一种破坏性行为。
所以一定要保护孩子对作业的兴趣，我的建议是把它变成一种奖励，而且最好以挑战的形式出现。
比如，你发现孩子不太喜欢写作文，就可以专门给孩子开设一个公众号，把孩子的作文晒出来。
本来作业只是交给老师的任务，现在却能被更多人看到并点赞，孩子一下子就会重视起来。而对于低年级的孩子，我们可以告诉他写完作业之后，会有哪些有趣的事情发生等等。

第六，寓教于乐，增强学习趣味性。
当孩子完成作业以后，我们可以用生动有趣的形式，讲一些跟新知识点有关的故事。
这样可以增强学习的趣味性，同时鼓励孩子积极回应，得到孩子对新知识点的反馈信息。长期坚持可以获得良性互动，让孩子不排斥学习，乐在其中。

第七，培养孩子学习的内驱力。
学习应该是他自己的事，培养孩子学习的内驱力的方法就是为孩子树立梦想、树立榜样。每一位孩子都值得拥有自己的梦想，我们要找到孩子的梦想，并为孩子树立强大的榜样。
放大他的梦想并与现实的学业相结合。就可以激发出孩子源源不断的内驱力。请记住，梦想对于孩子的驱动力，远远大于父母的管教。

第八，争取老师对作业的及时反馈。
如果这些你都做了，孩子做作业还是动力不足，那我建议你留心观察一下孩子做作业的细节，他是所有作业都拖拉，还是特别不喜欢做某一门的作业。
客观地说，孩子做作业拖拉，有时候和个别学校的老师缺少及时反馈有关。

定位了这类问题，我们就可以主动寻求老师的支持，用家庭和学校配合的方式，找到激发孩子完成作业的内在动力。
首先，你要和孩子商定一个时间范围，比如用两周时间改变做作业拖拉的问题。
再和老师沟通：“我和孩子定了一个两周改变拖拉习惯的小目标，希望能得到您的支持。
我会把孩子在家里完成作业的过程记录下来发给您，如果还不错，您可以表扬表扬他。如果他的问题是因为个别知识点不理解，还请您给他一些个别辅导。”

最后，我还要提醒大家，虽然现在很多学校，尤其是低年级，会要求家长给孩子的作业签字。但这并不意味着，你要给孩子检查批改，消灭错误，帮他交一份完美的作业。
相反，你要让孩子把错误暴露出来。因为作业是孩子给老师的学习反馈。我们要让孩子的错误暴露出来，这样老师才能及时的发现、纠正。
最后，我想告诉各位父母的是，陪读不如陪伴。作业的目的是培养独立学习的能力，让孩子享受学习的过程，并且发展出适合他这个年龄的规则感。所以，给孩子营造一个安静独立的学习空间，会更有利于他成长。


* Article: 放学后别催孩子写作业，先花10分钟做这件事，专治拖拉磨蹭
开学了，不止是孩子，陪读的家长也面临很多挑战。这两天留言板瞬间热闹起来，总结起来就是5个字：作！业！写！不！完！
不少家长说作业太多了，总要写好晚才行。好奇之下，和几个家长详聊一番，才发现不是作业多，而是写作业过程太......漫......长！

众多家长都在“投诉”孩子这几种情况：

:-)孩子写作业不主动，催都催不动。
:-)东张西望，作业不专心，磨磨蹭蹭耗时间，怎么催都没用。
:-)不会独立思考，遇到问题就停下来不动了。
:-)孩子凑合应付，作业完成万事大吉，家长每天查改的过程特别痛苦......

我相信很多家长都遇到过这样的问题，也都总是束手无策干着急。我以前遇一位家长，他家每天孩子做作业的时候就像是在打仗，家长陪孩子写作业时：嘴巴不闲，手不闲，各种暴躁抓狂。

孩子每写一字，每做一题，家长就开始叽里呱啦，叨个没完：

“这一撇咋就这么难看？”
“用橡皮别那么大劲”
“头抬起来……”
孩子题做错了，张口就是：
“脑子去哪了，都不想的？”
“刚才怎么跟你讲的，是不是傻？”
“又错，你怎么不想好再写”

看到孩子写字不端正，火气噌噌往上冒，抢过作业本，不管三七二十一擦掉，接着怒吼：“马上给我重写！”
孩子稍稍停顿，就开始凶：“现在几点啦，你想拖到什么时候……”

真是应了家长群里调侃的那句话：不写作业时，母慈子孝，连搂带抱；一到写作业，鸡飞狗跳，乌嗷喊叫……
如果家长陪着孩子写作业，孩子与家长都出现“精神分裂”状态，那么家长的“陪”要么是弄巧成拙，要么是多此一举。
换位思考一下，我们就可以理解。想一下平时我们做事情，为什么会拖延，多数情况下是因为我们觉得这个事情不容易，还有是不喜欢。当孩子从开始对写作业有种不得不做的情绪，那他怎么能好好地去完成？

孩子本身年纪小，专注力就会弱一些，家长一直坐旁边盯着，不断打扰，无形给孩子添了不少“堵”。再加之间歇性即兴咆哮，孩子整个写作业过程是非常不愉快且处于压迫和恐惧感中，就更难集中注意力，作出正确的判断了。
所以说，父母这种监工式的陪写作业，只会使孩子丧失对学习的信心和兴趣，这样一来不仅孩子的作业无法完成好， 而且其学习成绩也会下降。

那究竟要怎么陪，才能事半功倍？

这里需要提醒各位，陪写作业的目的是让孩子养成自我检查、独立思考的能力，才能更好的辅助孩子学习。
所以家长们在陪写作业的时候，一定不要本末倒置，忽视了孩子的主体地位。懂得这一点后，家长在陪伴孩子写作业的问题上就能游刃有余了。


想让孩子天天完成好作业并不难，关键是需要家长和孩子形成默契配合理解。下面就为各位家长们支几招：

** “做作业”3个必备
1. 相对安静的环境，齐全的学习用品。一颗安静的心！（如果孩子静不下来，强迫他作业做的效果只会适得其反）
2. “作业计划本”：让孩子按照不同学科，分条记录好每天老师布置的作业。及时提醒并对照，如果当日完成记上√，如果未完成，可继续加入之后的学习日程中。
3. “纠错本”，把暂时不会做的题目和做错的题目分别记录下来，便于之后重温、复习，反思不会做或做错的原因！

** “陪作业” 4步走
1. 预估：让孩子先预估完成每门功课的时间，让孩子根据自己的时间安排进行，到点家长要及时提醒，如果没按时完成，帮助孩子寻找原因；
   如果是拖拉，给孩子一定的缓冲时间继续完成，给孩子设定一些奖励，激励孩子尽早完成！
2. 检查：等孩子完成一门功课的作业后，给他一定的时间自己检查，控制在5-10分钟之内。如果孩子确定自己完成无误之后，家长再仔细检查。
3. 安排休息：根据孩子课业负担情况，合理安排做休息时间，让孩子从不同学科中转换思维。
4. 总结：在检查完孩子的所有功课后，如果孩子完成得好，及时表扬；如果出现错误，一定要耐心帮孩子进行错题分析；
   如果是因为粗心而出现错误，可以给孩子设定一些小惩罚，比如减少玩乐的时间、罚孩子做点家务或者做点体育活动等。让孩子牢记检查的重要性！

** “点拨做题”3个技巧
有的孩子，确实需要父母点拨那些“爬坡”难题，父母作出相应的辅导和点拨是必要的，也是必须的。只是在辅导、点拨时要讲究技巧：

1. 让孩子反复读题
许多题目不难，只是孩子缺乏耐心阅读原题，往往只看了一遍感到不会做，很难，这是一种消极的心理暗示。如果父母总是迁就孩子，立即告诉他如何做，甚至将版式列好，就会使孩子养成遇到问题不思考、依赖他人解决的坏习惯。
正确的方法是：“妈妈相信你，只要多读几遍原题，你会做出来的。”当孩子做出来以后，父母要高兴地称赞：“我说过吧，仔细读题就会做了。”这时孩子也一定会高兴起来.孩子不会做的题，父母坚持让他“再读一遍”“再读一遍”，不轻意告诉他，这种鼓励式的读题法能够“逼”出孩子主动学习的兴趣，从而获得自信。

2. 用例题作辅导
对于孩子经过思考也没做出的题目，父母也不要直接告诉他原题的解法，最好是根据原题编一个相似的例题，与孩子一起分析、讨论，弄懂弄通例题，再让孩子去做原题。
一般弄懂了例题，孩子多半会做原题，如果仍不会做原题，那么要再回到例题的讨论与计算上。经过几个来回，只要父母耐心引导，孩子一定会做原题的。这种做法虽然父母要麻烦一些，但能够训练孩子举一反三的迁移能力。否则，孩子总是就题解题的被动思维定式中，很难建立学习的思维迁移模式。

3. 只讲关键点
对于有些难题，父母一时也编不好例题，那么，可以就这个原题分析它的关键点在哪里，找到什么条件就好解题了，让孩子根据父母的提示去思考、列式计算。而不能将算式直接列出来，或告诉孩子第一步做什么、第二步做什么……如果这样辅导孩子，那么他的解题思路不容易打开。
当然，孩子逐渐长大后，许多爬坡题父母也无能为力，需要请家教辅导，那么还是建议父母要求家教按上述方法辅导孩子，不要一来就直接告诉孩子怎么列算式，怎么做题，如果这样看似难题解决了，其实孩子思路没有打开。

** “陪作业”5个提醒
1.孩子做作业时，尽量不要去干扰或打断他；
2.教会孩子使用二八法则
陪写作业时“授之以鱼，不如授之以渔”，小学中高阶段时，孩子留的作业可能会增多，做作业也需要一定的技巧。
这时候就需要二八法则的帮助了，即把难做的和容易做的分开，然后用80%的时间做难题，剩下20%的时间做相对容易的题目。
二八法则是指在任何一组东西中，最重要的只占其中一小部分，约20%；其余80%尽管是多数，却是次要的。把这种规律运用到学习上也是很有作用的。
一般来说，学习的重点跟难点只占全部学习内容的20%，我们却要把80%的精力投入在这些重点跟难点上面；
而其他内容虽然占了80%，我们只需花20%的时间就能掌握。
写作业的时候孩子这样做能大大提高学习效率，家长陪伴起来当然心情舒畅。

3.陪伴的目的是让孩子养成好习惯
在小学阶段，学习习惯的培养才是最重要的。好习惯就像是我们生命的枝上盛开的一朵美丽的小花，孩子能否养成良好的学习习惯，对他们的成功与否至关重要。

如何让孩子养成好习惯呢？当然需要循序渐进地来。
在孩子写作业时，家长可以专心读自己的书，父母认真读书的状态也会影响到孩子的，因为这本身就是一种很好的示范，就已经为孩子提供一个非常好的环境了。长此以往，何愁孩子养不成好的学习习惯？
4.家长应该教给孩子方法，引导孩子多动脑，而不是直接给答案！
5.最重要的是耐心！耐心！！耐心！！！


* Article: 孩子写作业潦草马虎怎么办
孩子写作业马虎潦草是一种不良的学习习惯，也能反映出孩子对学习的一种态度。
对于孩子写作业马虎潦草，家长只要发现了就一定要及时的进行纠正，适当的给予批评和惩罚，让孩子明白自己的行为非常不好，也让孩子以后改变对学习的态度。
一个好的习惯，真的会影响孩子一生，特别是学习习惯，一旦养成了坏习惯，改正起来是非常难的，所以一定要及早发现及早帮助改正。那么当发现孩子写作业马虎潦草的时候，作为家长该怎么办呢：

** 工具/原料: 耐心
方法/步骤:
1) 把马虎潦草的地方全部指给孩子看
孩子写作业潦草马虎的原因很多，有的可能是因为孩子着急出去玩，或者是因为作业量实在是太多，当然也很有可能是因为孩子对待学习的态度不是很好，所以导致孩子作业马虎。
不管是孩子因为什么原因导致孩子写作业马虎，做家长的一定要给孩子给孩子指出来，不管孩子是无心还是有意，都要一一指出给孩子看，让孩子自己看一下他的作业到底是一个什么样子。

2) 写作业时必须先让孩子“安心”
我记得我家宝贝很小的时候，因为写作业潦草被我狠狠惩罚了一回。可后来才知道，宝贝的同学和他约好了一起外出玩耍十分钟，然后再写作业。
我家宝贝都是先写作业，然后剩余时间再自己做些计划。结果那天我不知道是那么个情况，“硬逼”着宝贝写作业，结果孩子因为不安心所以作业写得马虎潦草。
在孩子写作业之前，一定要让孩子安下心来，没有任何“心事”的写作业，这样孩子才能一心一意写作业不至于马虎潦草。

3) 找出孩子认真写作业的“优秀作业”
我家宝贝写作业很认真，但就是字迹不是很漂亮。如果他认真写的时候还是很不错的，一旦稍不用心整体看起来就不是那么好看了。
有时候发现宝贝作业有些潦草的时候，我会一一翻看，然后找出那些写的非常漂亮的作业，让他自己进行一个对比，看看到底哪样的作业看起来更顺眼。
我不喜欢把孩子和别人家的孩子对比，那样会让孩子生出一股子怨气，更会让孩子有反感心理的。但可以和自己优秀的时候对比啊，这样孩子一看就明白自己该怎么办了。

4) 一旦发现让孩子重新写一遍
这一点是必须的，不能因为孩子求饶或者装可怜你就任其孩子的作业潦草马虎。
字啊你发现孩子的作业很马虎潦草的时候，直接告诉孩子这样是绝对不可以的，让孩子把那些作业重新写一遍，一定要认认真真按照规范写。如果孩子写的还是马虎潦草，那么就要再来一遍，直到作业不再马虎潦草为止。让孩子明白，靠撒娇或者糊弄就能蒙混过关是不可能的。

5) 一定要检查孩子作业
孩子都有一定的惰性，再一个天生好玩是孩子们的共性。现在孩子的作业量也是非常多，每天回家写完作业基本上就是吃饭洗漱然后睡觉了，几乎没有玩的时间。
那么孩子再写作业感到疲惫，或者厌烦的时候，就会马虎潦草态度不端正。这时候家长要是不检查孩子作业，孩子就会“蒙混过关”，下一次孩子还是会这样做的，一旦养成习惯就不好了。

6) 联合孩子老师一起改正
孩子在家我们可以用心照看着、教育着，可孩子一旦离开我们身边，我们就不可能那么面面俱到的看着孩子了，比如孩子在学校的时间。
虽然孩子会有老师教育着约束着，可老师要面对的不只是一个孩子，那么对于孩子的行为可能不是那么很细致。你要和老师经常联系，让老师辛苦辛苦，帮着你一起修掉孩子写作业马虎潦草的习惯。

7) 给孩子一个安静的写作业环境
不用说孩子了，就是我们大人，在做事情的时候要是环境不够安静，肯定也是静不下心来专心做事情。
在孩子写作业的时候，家里的环境一定要保持安静，不要有别人在边上吃东西或者游戏，并且室内的温度要适中。
特别是在这个季节，不能让孩子感觉到手冷，那么写作业的时候孩子一定会想着快点写完，自然就会出现马虎潦草了。
在孩子写作业的时候，你可以偶尔看一下，但最好不要一直盯着孩子写作业，更不要子啊边上玩手机或者做其他让孩子不能安静的事情。

8) 孩子写作业时最好不要“扎堆”

孩子们喜欢聚堆，一群孩子在一起做什么都会很开心的，就算是吃饭孩子们只要在一起，饭量也是显得格外大。
孩子一个人在家会有些孤单，所以有些孩子或者家长会选择让孩子和自己的同学一起写作业。
可如果孩子们不是很用心的话，那么只要一个的作业马虎潦草，很容易“传染”给其他孩子的。再一个孩子们在一起嘻嘻哈哈，写作业的时候肯定不是那么用心，难免会出现马虎潦草的事情。



* Article: 如何辅导容易分心的孩子做作业
孩子偶尔会匆匆忙忙写功课是因为他们可以有更多时间做自己想做的事，但对于容易分心的孩子，匆忙写功课是一个持续的挑战，这通常会导致作业潦草、出现错误或者不能完成。
这通常归咎于执行功能问题，它们可以影响孩子的一切，从信息的储存到自我监管。

** 下面是一些容易分心的孩子“赶作业”的常见原因：
1) 疲劳
白天在学校里，容易分心的孩子往往将他们的精力用于听课及试图应对各种各样的要求。
回到家时，他们已身心俱疲。放学后如果没有得到足够的休息，可能会引起他们匆匆忙忙写作业，而这仅仅是因为他们没有足够的精力来集中注意力。

2) 信息储存困难
容易分心的孩子可能会发现他们的想法变化得比他们讲出来的速度要快得多。
举个例子，当你让孩子解释内战的原因，他可能无法让他的想法保留足够长的时间去组织和阐述它们。
相反，他可能会尽可能快地在想法消失前潦草写下答案。这也就意味着孩子不能回答甚至是给出错误的答案。

3) 糟糕的时间管理技巧
当孩子容易分心时，通常会面对各种各样的问题，他们可能会在每项任务的时间分配上估计不足。
他们在一项任务上超级专注以至于他们转移到下一项任务就会有困难。如果已经在一项任务上花费了一个小时，剩下的任务他们可能就会匆匆忙忙地完成。

4) 难以保持长久兴趣
容易分心的孩子很快会对重复又重复的事丧失兴趣。研究表明注意力缺失的人大脑中的多巴胺水平较低，这会使他们很难应付那些冗长乏味的事。比如说，面对25道非常相似的算术题时，孩子可能就会随便写，那是因为他觉得非常无聊。

5)感觉挫败
在学校里做的不够好的话，孩子可能就会觉得很挫败并且丧失自信。久而久之，他们会逐渐相信不管他们多努力尝试或者学了多少，他们还是不能得到一个好成绩。
当孩子认为不管他花20分钟还是2小时在功课上结果还是一样的，他们可能就会觉得不值得花时间认真地写了。

6) 各种学习挑战
容易分心的孩子通常也会伴有学习问题，比如阅读障碍、书写障碍或计算困难等。注意力缺失最主要的挑战是他们难以应对要处理的任务，因此，孩子们为求完成任务，可能会匆忙潦草地写完。

7) 难以自我监控
对于容易分心的孩子来说，写作业仿佛是无穷无尽的。因此长时间坐在位置上检查作业的错误对他们来说可能是难以忍受的，他们可能也会认为付出一次努力就可以了。
如果他们知道作业完成后还要再检查一遍而不是直接交上去被评分，这可能会引起一个更大的问题。

** 有多种原因可能会引起分心的孩子匆忙潦草地写作业，执行功能问题和注意力缺陷障碍则会使这种情况更加严重。但是还是有很多办法可以帮助你的孩子慢下来，尝试下以下的策略吧。
1) 固定写作业的时间
每周为写作业留出一段特定的时间，你甚至可以使用“写作业合约”来制定时间表。有约定的时间可以帮助孩子养成到时间要写作业的想法，同时也可以避免他“赶作业”好赶紧去玩的念头。
对小学生来说，最好是以20分钟为基准。比如说你的孩子现在是三年级，那他就应该每天大约花60分钟在功课上。如果他提前做完了，那他就可以看看书或者玩玩教育类的电子游戏。

2) 使用计时器
你可以用电脑、手机APP、秒表甚至沙漏，将孩子的作业分时段，在每项功课的末尾设定提示。鼓励孩子不间断地完成作业直到计时器响。有一个可视的或可听的“提示”可以让孩子形成每项作业应该花多长时间的感觉。
同时也提醒他有一段设定的时间，这可以帮助他提高注意力。

3)帮助他形成写作业的正确心态
如果你的孩子经过白天的事已经变得精疲力竭了，他可能就只想把作业写完就算了。当他看上去很疲劳或者很不安，可以等一会再让他做功课。可以让他到外面跑跑步或者安静地玩一会，这样可以帮他减轻压力。
当到时间写作业的时候，他就会有精力来尽他最大的努力。

4) 如果孩子需要慢下来，就即刻干预
如果你注意到孩子在“赶”，不要等到他写完了才去干预，而是在当下就应该试着使他慢下来。检查过程中你可以问类似的问题：“你尽最大的努力完成功课了吗？”或“老师可以看得懂你写的作业吗？”如果你在他写完之前就指出正确的答案而不是要求他之后重做，这对你们来讲都相对比较容易，同时也可以让孩子形成良好的习惯。

5) 鼓励孩子检查作业
在孩子认为已经写完作业之前，要提醒孩子检查他因为不小心或马虎写错的作业。你甚至可以为他制定一个检查清单：他是不是遵照作业要求？单词都拼写对了吗？大写字母都用对了吗？他可以读出他所写的字吗？
帮助他形成检查作业的习惯可以让他建立写好作业的标准，也可以使他为自己的转变感到自豪。

6) 帮他将任务细分
从四、五年级开始，功课会要求运用更多时间管理和组织技能。孩子们会有越来越多及越来越难的任务，不仅仅是到第二天就要交的简单的作业任务，有可能上交的截止时间会更晚。
你需要帮助孩子计算出怎样在一段长久时间里留出足够的时间完成充满挑战的作业。制作一个学习日程表将任务细分，这可以帮助孩子预期自己可以按照平稳的脚步一点一点地完成功课。

7) 多点表扬他的长处
许多在学业上不太成功的孩子可能也不会自信有可以将功课写好的能力。所以他们可能就会马马虎虎，认为不值得去努力。多点表扬孩子的长处，谈一谈他曾经在某一件事上非常努力，并且最终取得了成功，不管这事是大是小。
这可以增强孩子的自信心，同时可以让他带着一个积极的态度来完成功课。

8) 给他所需要的帮助
有些孩子让作业登记簿空着或者匆忙潦草地写作业是因为他们让作业给搞得沮丧极了。
他们可能有影响阅读、书写或算数技能的学习障碍。如果你觉得这可能是影响孩子的原因，你可能需要和老师谈一谈，跟老师谈谈你观察到的事情并且询问老师所观察到的东西。
你们可以一起商量下一步应该做些什么来帮助孩子。你可能会想要一份评估，你的孩子可能在技能和适应上需要一些特别的指导帮助他成功。
孩子越早得到他需要的帮助，他就能越早将注意力集中在学习上。




* Article: 家长不要这么说，否则孩子将更厌恶写作业
眼看着暑假还剩一周，在准备新一学期之前，抽空看一下孩子的暑假作业，或许会有“惊喜”！
一个朋友，孩子马上上3年级，今天查了一下孩子的暑假作业，把她惊呆了！
她说，字写得东倒西歪，写字所谓的横平竖直没一毛钱关系。
有的字还多一横，或者少一笔...
不知道写作业时，孩子是不是着急出去玩。看了一下数学题，好多都是错的，一看就知道是在应付差事。
之前写作业的时，当时就跟他说过，字写得太潦草了，让他把字写认真一点。不过这些话，根本听不进去，愁死个人！

相信不少家长在孩子写作业的时候，也会为此苦恼。
对于孩子不认真写作业，我们该怎么帮助孩子呢？

一个提示：
*越否定孩子，孩子就越会往不好的方向发展！*

所以，
要一边肯定孩子，一边把我们的想法告诉他。
人人都希望自己是受关注的那一个。
越是受到关注的行为，就越会去做，不管结果好坏！
家长不会这么说，孩子将更厌恶写作业

我们经常看到电影的情节：一个想轻生的人，站在楼顶，没过多久，就有很多人在楼下围观。
或许站在楼顶打算轻生的那个人，可能只是一时想不开，也是犹犹豫豫的。
可楼下那么多人围观，受到极大的关注，甚至一些新闻媒体也来报道。
本身犹犹豫豫的心态，突然受到这么大的关注，搞得好像不做这件事，都说不过去了，再加上楼底的人的怂恿，可能就真的一跃而下，酿成悲剧。
当然，这是电影里演的情节，但也能一定程度上说明了：越是受到关注的行为，就越会去做，不管好坏！

回到孩子写作业上，

孩子都想早点儿写完去玩。爱玩是孩子的天性，是好事，但应付作业确实让各位家长头疼。
出于关心，我们直接指出孩子的缺点，目的是想让孩子改正，但常常事与愿违。

那是因为，我们越是关注孩子写不好作业，没写好作业就会占据孩子的脑袋，就越被关注，这时，孩子内心会产生极大的情绪内耗，反而更写不好作业，从而导致这样的行为越来越严重。
有时候，你是不是也一样？
心里很想去做一件事，就是拖着没去做，不过心里又一直挂念着。周末在家躺一天，也没做什么事情，莫名其妙的感觉特别累！这就造成了极大的情绪内耗。
到最后，事情还是没解决，或者草草了事。

所以，孩子写不好作业时，更应该去肯定孩子！
“是准备把作业做完再出去玩么？
真不错！我的宝贝长大了哈，知道要先把重要的事情先完成再去玩了！
妈妈知道你很想快点出去玩，如果你能耐下性子把字写好，把作业写完，那你就拥有了一项伟人的特质哦！我在一本书里看到，毛主席能在熙熙攘攘的环境中专心读书写字！厉害吧！”


别人的缺点、不足，很容易被我们注意，这是很自然的事情。
而从别人身上找到做得好的事情，这个能力可不是所有人都熟练掌握的。
为了孩子的成长，我们家长还是尽量减少批评，减少负面评价，多给孩子肯定。

比如，孩子把作业写得很潦草，急忙出去玩了。
那我们可以捕捉到，孩子起码有：先写完作业再出去玩的意识，这就值得表扬！
孩子回来后，说写作的事情时，我们可以话术优化一下，
比如：“今天是写完作业才出去玩的吧！不错！自己主动做完才去玩，值得表扬一下！如果能静下心把字写得认真一些，那就更好了！回头你去看下，有些地方看看要不要修改一下？”



* article: 小学学习是孩子一生勤奋的开始
小学阶段的学习是让家长最头疼的：抓得紧一点吧，怕累着孩子，更怕孩子在压力之下失去学习兴趣；追求快乐教育吧，还有点没底气，怕孩子瞎玩好几年最后一无所获……

如何才能让孩子度过一个充实又有意义的小学生涯，还能在初中保持学习的先发优势？
** 一、二年级 —— 关注学习习惯
*** 字迹工整：小学练字偷小懒，初中做题吃大亏

说得实际点，无论是写作业还是答考卷，清晰、工整的字迹都能让老师心情愉悦，酌情加分不在话下；字迹清晰，也能减少老师因看不清学生写的什么而造成的误判；
握笔姿势正确，字迹工整，能提高孩子的书写速度，要知道，写得既快又好，是对高年级孩子非常重要的一项能力。
如果一二年级不注意孩子的握笔姿势、笔画顺序、字迹工整等细节，一旦养成了写字潦草的习惯，今后再想改就难了。

*** 写作业速度：拖拉不是病，改起来真要命
很多孩子写作业的时候不是要喝水、吃水果，就是要上厕所，结果本来不多的作业总要磨蹭到很晚才写完，而且错误百出、字迹潦草。
看一个孩子写作业的速度，基本上就能推测他的学习情况。

所以，陪一二年级孩子写作业的时候，不妨先领他回顾一下当天的课堂知识，做好准备工作；然后一起制定一个计划，精神状态好的时候先做不擅长的作业；当然，写作业过程中要及时纠正孩子的坐姿、握笔姿势等细节。

*** 打扎实字词句的基础
对于1年级的孩子来说，大部分都是零基础入学的。在这里我建议家长，如果你们希望自己的孩子在入学之后比较轻松的话，那就需要在学前培养孩子的阅读能力了。
当孩子具备自主阅读能力之后，在1-2年级阶段，我们就可以将重点放在基础字词的背默上了。
所以，在1、2年级阶段，我们必须要帮助孩子将字词句的基础打扎实，这是非常重要的。

如何帮助孩子识记字词？

1、识记词的注音、字形、意义及生成义
2、看字词在文中具体是怎样运用的
3、用字词造句
4、联词成篇

** 3-4年级的学习重点 —— 阅读+写作
小学3-4年级，孩子自身的年龄特征和认知能力会不断提升，所以这是培养孩子阅读写作能力的重要时期，这也许会直接决定孩子对语文的态度。
阅读方面：培养阅读习惯，勤动笔写作

三四年级的语文课，重点逐渐由“拼音”“字词”向“文章理解”过渡，而让孩子更好适应这个变化的最好办法，就是多阅读课外书。

三年级的作文，也由“写几句话”向“写一篇完整的文章”过渡，这是很多孩子的难点。如果写作基础在这一段时间打不好，到了高中仍然是个大麻烦。而训练写作最好的方法，就是勤动笔写日记，关键不在于每天写多少字，而在于每天都坚持。
除此之外，如果孩子有时间和精力的话，建议家长在3年级阶段穿插着将校内规定的100多首古诗词背默完，这样4年级就可以让孩子慢慢接触小古文了。
四年级学古文的时候，家长可以将重点放在一些成语或寓言故事上，让孩子了解文章的大概意思，如果能理解重点句子那就更好了。这样过度到古文也会相对轻松一些。


** 4年级下-5年级上的 —— 学习重点
这个阶段家长就可以引导孩子进行系统复习：基础字词句的查缺补漏，古诗文的背默，阅读写作技巧的归纳总结。
具体内容包括：

1. 反复默写基础字词
2. 复习小学阶段所有的古诗（背默+作者及创作背景等内容+经典句子）
3. 复习学过的古文（文章的大意+经典句子/关键词的理解）

** 5年级下-6年级的 —— 学习重点
五六年级关注重点：强化基础知识，保持孩子良好心态

无论招考政策怎么变，打好基础才是根本。五年级上学期开始，语、数、外各科的难度有所加大，而且很多都是小升初考试的重难点，如果这一阶段遗留太多问题，肯定会对小升初有影响。
所以一定要做好错题的归纳整理工作，之前一直没有错题本的，也该建立一个了。不过，把错题一字不差地抄一遍并没什么用，关键是要经常翻看，把以前出过错的题型烂熟于心。只要能保证以前错过的题型、知识点下次不再错，就已经抓住了一半的分数。
进入六年级，就是紧张的小升初备战了。这一年里，心态非常重要，很多孩子因为过于紧张，或者父母期望高、压力大，导致考试失利。所以，给孩子营造一个宽松、温馨的家庭氛围就好了，千万不要因一个小升初考试搞得大张旗鼓。高考都无法决定人的一生，何况区区小升初考试。


* article: 孩子为什么不爱写作业 家长你反思自己的原因了吗？
每次看到孩子写作业，亲妈一定会变成后妈，孩子怎么就不写作业呢？写作业五分钟都安静不下，就开始有小动作了。
小学生本身定性就差，再加上作业不是自己想写的，就更没有耐心做些来写作业了。孩子不写作业不仅仅是孩子的问题，家长也有不可推卸的责任。
孩子在写作业的时候你在做什么？孩子写作业磨蹭你是怎么做的？孩子晚上不睡觉你做了什么呢？孩子写作业潦草你责备了吗？
亲爱的各位家长，孩子的问题不是他自身的问题，你也应该反省一下自身的问题！

** 1、孩子正在写作业时，您在干什么？
[错误做法]：一边看电视一边监督孩子，嘴里不停叨叨：“写快点。”“别磨蹭。”“不准看电视，好好学习。”
[结果]：孩子不高兴：“凭啥你就能看电视，我就不能看，真不公平。”
[正确做法]：大人也看书，不打扰孩子，营造浓厚的家庭学习气氛。
[结果]：孩子心态平和，心思都在学习上。

** 2、孩子写作业磨蹭、拖拉、不专心，该睡觉了，作业却没写完。您会怎么做？
[错误做法]：训斥孩子：“你气死我了，怎么又没写完，我一会儿不看着都不行，快点写！我看着你。”
[结果]：孩子并不着急，依然慢慢悠悠看。
[正确做法]：严肃地、平静地对孩子说：“孩子，写作业是你自己的事，你要对自己的事负责，没写完不准写了，该睡觉了，明天自己去学校跟老师解释吧。”（适当地让孩子承担自己的行为带来的一些后果。）
[结果]：孩子意识到自己的错误，很后悔，心里想：“这下完了，怎么跟老师说呀，看来明天写作业得快点了，不然还得挨批。”

** 3、孩子一直看电视，不睡觉也不写作业，您怎么做？
[错误做法]：怒气冲天地把电视关掉，吼叫着叫孩子去写作业或睡觉。
[结果]：孩子满肚子不高兴地去了，心里恨你，说你是暴君。
[正确做法]：平静对孩子说：“孩子，你该写作业了，如果写不完会挨批。你还想看多久？”孩子：“我再看10分钟行吗？”家长：“行，说话算数，到时间就关电视。”双方各退一步。
[结果]：时间到了，孩子主动关电视，去睡觉或写作业。

** 4、孩子作业写得潦草，您怎么做？
[错误做法]：发火：“怎么写得这么乱，你就不能写好点？”甚至气的把孩子的作业撕了。
[结果]：孩子茫然，不知所措。
[正确做法]：严肃地、平静地对孩子说：“孩子，我已经说过了，写不工整要重写，因为不工整，老师看不清楚，你看，这是“规定”，不能破坏，所以你必须重写了。
你看，你应该这样写字（讲述写字规范，横平竖直，大小一致。）。孩子，你只要写得比你刚才的字有进步就行（和自己比），有信心吗？”
[结果]：孩子懂得“规定”的重要性，心里想：“比刚才的字有进步，容易。”孩子会对自己充满信心。


** 5、孩子考试不及格，您看到成绩单后怎么做？
[错误做法]：训斥孩子：“你看你，考这么点分，你也不嫌丢人？你看人家谁谁，人家怎么就能考一百？你笨死了！气死我了。”更有甚者使劲踢孩子几脚。
[结果]：孩子心情坏到了极点，心里想：“我完了，我这么笨，学不好了，再怎么学也学不好。”
[正确做法]：安慰孩子：“孩子，我知道你心里也不好受，一次没考好不代表什么，关键是我们要找出没考好的原因，然后解决它，好不好，我和你一起分析一下。我相信你，下次一定会有进步。”
[结果]：孩子认真地找原因去了，心里想：“我要努力，不辜负爸爸妈妈的期望，我一定行。”

** 6、家长会上，老师告孩子状、您挨老师批评了，回到家中您会怎么做？
[错误做法]：一回家就把气撒在孩子身上，对孩子又打又骂。
[结果]：孩子没任何自信，要么学会暴力，要么胆小，一句话不敢说，学会撒谎，不敢和父母说真话。
[正确做法]：先把孩子的优点讲讲，然后分析不足的原因，鼓励孩子，相信孩子下次一定会有进步。
[结果]：孩子会给你惊喜的哦！

** 7、孩子见人不打招呼、没礼貌，这时您该怎么做？
[错误做法]：当众训斥孩子：“你这孩子怎么这么没礼貌？连问好都不会，我平时是咋教你的，没出息。”
[结果]：孩子的自尊心受到很大损伤，觉得无地自容，自卑感油然而生。
[正确做法]：给孩子台阶下：“我孩子有点不好意思，慢慢就好了，他平时也挺有礼貌的。”举个有礼貌的例子”
[结果]：孩子知道错了，心想：“这次没做好，下次一定做好，不能让父母失望啊。”

** 8、孩子问了个问题，您不会，这时您会怎么做？
[错误做法]：不高兴：“别瞎问了，把学习搞好就行了，每天不知道想点啥。”
[结果]：孩子心里想：“哎，没劲，总说学习学习，烦死了，不问就不问。”从此，遇到难题一概略过，不求甚解。
[正确做法]：高兴地对孩子说：“孩子，你能问这么难的问题，证明你动脑筋了，不错。可是我也不会，咱们一起研究研究吧，好吗？”
[结果]：孩子心里很高兴，以后遇到问题一定锲而不舍，非研究明白不可。

孩子的家庭教育很重要，有些事情，对孩子的教育不注意，容易造成孩子的逆反心理。
